version: "3.6"

services:
  api:
    build:
      context: .
      dockerfile: EncryptionService.API/Dockerfile
    ports:
      - 5090:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - LAST_KEY_QUANTITY_USE_TO_DECRYPT=5
      - KEY_LENGTH=16
    volumes:
      - ./:/EncryptionService.API
  gateway:
    build:
      context: .
      dockerfile: EncryptionService.API.Gateway/Dockerfile
    ports:
      - 5063:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - OCELOT_CONFIGURATION_FILE=ocelot-docker.json
    volumes:
      - ./:/EncryptionService.API.Gateway